# Generated by Django 2.2 on 2021-04-27 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='user_like',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='wish_app.User'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
