# Generated by Django 2.2 on 2021-04-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0003_auto_20210427_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='user_like',
        ),
        migrations.AddField(
            model_name='wish',
            name='user_like',
            field=models.ManyToManyField(related_name='user_likes', to='wish_app.User'),
        ),
    ]
